name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: get tag
      id: tag
      run: echo "TAG=$(git describe --dirty --tags)" >> "$GITHUB_OUTPUT"
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        tags: hsmade/growatt_esphome:${{ steps.tag.outputs.TAG }}
        push: false
